version: "3.8"

services:
  flask_app:
    build: .
    container_name: flask_api
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/flask_app

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: